apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: encrypter
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: email@example.com
    privateKeySecretRef:
      name: encrypter-tls
    solvers:
    - http01:
        ingress:
          class: nginx
