apiVersion: apps/v1
kind: Deployment

metadata:
  name: goserver
  labels:
    app: goserver

spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"

    spec:
      containers:
        - name: goserver
          image: "jonasexplore/hello-go:v4.1"

          resources:
            requests:
              cpu: 100m
              memory: 20Mi
            limits:
              cpu: 500m
              memory: 25Mi

          livenessProbe:
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1
            httpGet:
              path: /healthz
              port: 80

          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret

          volumeMounts:
            - mountPath: "/go/config"
              name: config
      
      volumes:
        - name: config
          configMap:
            name: configmap-config
            items:
              - key: host
                path: config.txt
